[package]
name = "tokenmint"
version = "0.1.0"
authors = ["elaineo <elaine.ou@gmail.com>"]

[dependencies]
bincode = "0.8.0"
nickel = "*"
leveldb = "*"
serde_derive = "1.0"
serde = "1.0"
serde_json = "1.0"
plugin = "0.2.6"
typemap = "0.3.3"
gethrpc = { path = './gethrpc' }